// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TVManager_Infrastructure;

#nullable disable

namespace TVManager_Infrastructure.Migrations
{
    [DbContext(typeof(TVManagerDBContext))]
    [Migration("20240820112920_update type of releasedate in tvshow model")]
    partial class updatetypeofreleasedateintvshowmodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TVManager_Domain.Attachment", b =>
                {
                    b.Property<Guid>("AttachmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttachmentID");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("TVManager_Domain.Language", b =>
                {
                    b.Property<Guid>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageID");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageID = new Guid("8542701e-340a-4bd8-b00d-4990cbb67c73"),
                            Name = "Arabic"
                        },
                        new
                        {
                            LanguageID = new Guid("83efb796-df81-4caa-b173-43d3ce6dc7d3"),
                            Name = "English"
                        },
                        new
                        {
                            LanguageID = new Guid("e0b27e76-54cd-485b-8994-552dc8f1a62d"),
                            Name = "France"
                        });
                });

            modelBuilder.Entity("TVManager_Domain.TVShow", b =>
                {
                    b.Property<Guid>("TVShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttachmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TVShowID");

                    b.HasIndex("AttachmentID");

                    b.HasIndex("LanguageID");

                    b.ToTable("TVShows");
                });

            modelBuilder.Entity("TVManager_Domain.TVShow", b =>
                {
                    b.HasOne("TVManager_Domain.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TVManager_Domain.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Language");
                });
#pragma warning restore 612, 618
        }
    }
}
